### ISSUE TITLE
Installing mamba

### ISSUE THREAD

**Issue by jc-hunink** [Deltares/iMOD-Documentation#8]
At the default installation of mamba, mamba is not added to the PATH. mamba is then not recongnized

**Comment by JoerivanEngelen** [comment]
Hmm strange. What do you mean with "default installation of mamba", did you run ``conda install mamba`` yourself? Or did you install Mambaforge? 

In case the first, did you install mamba in the base environment?

In case the latter, did you tick the "add to PATH" tickbox in the install wizard?

**Comment by jc-hunink** [comment]
I used the mambaforge installation. This issue was indeed fixed after tick the "add to PATH" tickbox. Because in the default installation of mambaforge this is not advised, maybee an extra remark can be added to the installation description (despite this is not an imod-python isssue but more a general python issue).

**Comment by Huite** [comment]
This section does mention it, but it's in the FAQ.

https://deltares.gitlab.io/imod/imod-python/faq/python.html#anaconda-miniconda-miniforge-mambaforge

But we should add a clause in the main installation instructions, maybe in a note box.
